settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 0
  host: ""
schema:
- name: NothingsBland.com
  path: ./web
  commands:
    install:
      status: false
    build:
      status: true
    run:
      status: false
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
    scripts:
    - type: after
      command: ./web
      global: false
      output: true
