# GOAL
# To build a development environment managed entirely within docker.
# Golang + Docker as an alternative to python (virtualenv) and vagrant.

# Concerns: host IDE is going to eat shit when searching for dependencies locally.

FROM debian:latest

ENV GOPATH /go:/
ENV GOBIN /go/bin
ENV PATH $PATH:/go/bin
ENV PATH=$PATH:/usr/local/go/bin

VOLUME /apps/nothingsbland/web
VOLUME /apps/logs

# updates
RUN apt-get update -qq && \
    apt-get install -y -qq wget git

# install golang
WORKDIR /tmp
RUN wget https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.9.2.linux-amd64.tar.gz

# install go-wrapper
COPY ./docker/go-wrapper /usr/local/bin
RUN chmod 775 /usr/local/bin/go-wrapper

# make volume directories
RUN mkdir -p /apps/nothingsbland/web
RUN mkdir -p /apps/logs

WORKDIR /apps/nothingsbland/web

# Dependencies
RUN go get github.com/tockins/realize

# ENTRYPOINT ["realize", "start"]
#CMD bash -c "realize start > logs/docker.log 2>&1"

# simple entry point for continuous server
ENTRYPOINT ["tail", "-f", "/dev/null"]

# Helpful Commands
# docker exec -t -i 50f331760ba7 /bin/bash
# docker remove $(docker ps -aq)
# docker rmi $(docker images -q)
# docker start -a -i `docker ps -q -l`


# docker build -t nothingsbland-img-dev -f Dockerfile-dev.
# docker run -tdi --name test nothingsbland-img